version: "3.7"

services:
  coin:
    image: tipbotapp/coin
    networks:
      - tipbotapp
    labels:
      - traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*

  discord:
    image: tipbotapp/discord
    networks:
      - tipbotapp
    labels:
      - traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*

  dogecoind:
    image: tipbotapp/dogecoind

  website:
    image: tipbotapp/website
    networks:
      - tipbotapp

  # https://containrrr.github.io/watchtower/
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 15 --label-enable --no-pull
    container_name: watchtower

  # https://docs.traefik.io/
  traefik:
    image: traefik:1.7
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - tipbotapp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
    container_name: traefik

networks:
  tipbotapp:
    external: true
