version: "3.7"

services:
  coin:
    image: tipbot/coin
    networks:
      - tipbot
    labels:
      - traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*

  discord:
    image: tipbot/discord
    networks:
      - tipbot
    labels:
      - traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*

  website:
    image: tipbot/website
    networks:
      - tipbot

networks:
  tipbot:
    external: true
