version: "3.7"

services:
  coin:
    image: tipbot/coin
    networks:
      - tipbot
    labels:
      - traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*

  discord:
    image: tipbot/discord
    networks:
      - tipbot
    labels:
      - traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*

  website:
    image: tipbot/website
    networks:
      - tipbot

  # https://containrrr.github.io/watchtower/
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 15 --label-enable --no-pull
    container_name: watchtower

  # https://docs.traefik.io/
  traefik:
    image: traefik:1.7
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - tipbot
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
    container_name: traefik

networks:
  tipbot:
    external: true
